### PR TITLE
Fix for Discord class changes

### PR DESCRIPTION
**Pull request by asportnoy**
Discord class changes broke the unread indicator.

### CODE REVIEW

**Comment by LuckFire** [comment]
not too sure what this is fixing, theme works perfectly fine on both canary and stable builds. none of the classes were even rerolled for something to break. would appreciate some more elaboration 👍

**Comment by asportnoy** [comment]
On channels where your notifications are set to only @mentions, Discord seems to have removed the `.modeUnread-3Cxepe` class. This is how it looks without the plugin:
Screenshot on 2022-08-20 at 09 04 53
The `unread-36eUEm` class still exists for the dot before it, so I used that instead.

It's possible this is some A/B thing, as it seems like Discord might be trying to have people enable more notifications? I don't know.

**Comment by LuckFire** [comment]
Just to make sure, it isn't some sort of plugin you have enabled is it?

**Comment by asportnoy** [comment]
Yes, I can still reproduce with no plugins.

**Comment by LuckFire** [comment]
Okay. I'll leave this opened for now since it's most likely an A/B thing. Discord also could have accidentally removed this class with it but I'm not too sure.

**Comment by asportnoy** [comment]
FWIW, I don't think it's accidental. Discord added a banner to channels with notifications set to @mentions, telling people to set it to all messages. And the class is still there if it's set to all messages. This also fits with the various notification related changes Discord has been making, like redesigning the unread messages bubble:
image

**Pull request closed without merging**
